#!/usr/bin/env bash
set -euo pipefail

cd /root/chatterbox
export CHATTERBOX_ROUTER_BACKENDS="${CHATTERBOX_ROUTER_BACKENDS:-http://127.0.0.1:8000}"
export CHATTERBOX_ROUTER_REQUEST_TIMEOUT="${CHATTERBOX_ROUTER_REQUEST_TIMEOUT:-600}"
export CHATTERBOX_ROUTER_QUEUE_TIMEOUT="${CHATTERBOX_ROUTER_QUEUE_TIMEOUT:-900}"
export CHATTERBOX_ROUTER_HEALTH_TIMEOUT="${CHATTERBOX_ROUTER_HEALTH_TIMEOUT:-5}"
export CHATTERBOX_ROUTER_CHUNK_LONG_TEXT="${CHATTERBOX_ROUTER_CHUNK_LONG_TEXT:-0}"
export CHATTERBOX_ROUTER_CHUNK_CHARS="${CHATTERBOX_ROUTER_CHUNK_CHARS:-270}"
export CHATTERBOX_ROUTER_CHUNK_SILENCE_MS="${CHATTERBOX_ROUTER_CHUNK_SILENCE_MS:-0}"

exec /root/chatterbox/.venv/bin/python -m uvicorn chatterbox_router:app --host 0.0.0.0 --port "${PORT:-8010}"
