#!/usr/bin/env bash
set -euo pipefail

cd /root/chatterbox

# Explicit opt-in profile for the fastest measured BC-250 Vulkan path.
# This is listen-before-default: it uses one-step S3, native T3 sampling,
# padded required Vulkan S3, no watermark, and fused split8 S3 midblocks.
if [[ -n "${CHATTERBOX_VK_DEVICE_SELECT:-}" ]]; then
  export MESA_VK_DEVICE_SELECT="${CHATTERBOX_VK_DEVICE_SELECT}"
  export MESA_VK_DEVICE_SELECT_FORCE_DEFAULT_DEVICE="${MESA_VK_DEVICE_SELECT_FORCE_DEFAULT_DEVICE:-1}"
fi

export CHATTERBOX_APPLY_WATERMARK="${CHATTERBOX_APPLY_WATERMARK:-0}"
export CHATTERBOX_S3_TIMESTEPS="${CHATTERBOX_S3_TIMESTEPS:-1}"
export CHATTERBOX_T3_NATIVE_SAMPLER="${CHATTERBOX_T3_NATIVE_SAMPLER:-1}"
export CHATTERBOX_ALLOW_VULKAN_S3_PADDING="${CHATTERBOX_ALLOW_VULKAN_S3_PADDING:-1}"
export CHATTERBOX_REQUIRE_VULKAN_S3="${CHATTERBOX_REQUIRE_VULKAN_S3:-1}"
export CHATTERBOX_T3_MAX_GEN_LEN="${CHATTERBOX_T3_MAX_GEN_LEN:-376}"
export CHATTERBOX_DEFAULT_SEED="${CHATTERBOX_DEFAULT_SEED:-20260708}"
export CHATTERBOX_VULKAN_S3_FUSED_MIDBLOCKS="${CHATTERBOX_VULKAN_S3_FUSED_MIDBLOCKS:-1}"
export CHATTERBOX_VULKAN_S3_FUSED_VARIANT="${CHATTERBOX_VULKAN_S3_FUSED_VARIANT:-split8}"

exec /root/chatterbox/run_api_vulkan_hybrid.sh
