#!/usr/bin/env bash
set -euo pipefail

cd /root/chatterbox
export HF_HOME="${HF_HOME:-/root/.cache/huggingface}"
export CHATTERBOX_DEVICE="${CHATTERBOX_DEVICE:-cpu}"
export CHATTERBOX_TORCH_THREADS="${CHATTERBOX_TORCH_THREADS:-2}"
export CHATTERBOX_TORCH_INTEROP_THREADS="${CHATTERBOX_TORCH_INTEROP_THREADS:-1}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-${CHATTERBOX_TORCH_THREADS}}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-${CHATTERBOX_TORCH_THREADS}}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-${CHATTERBOX_TORCH_THREADS}}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-${CHATTERBOX_TORCH_THREADS}}"
export CHATTERBOX_PROGRESS="${CHATTERBOX_PROGRESS:-0}"
export HF_HUB_DISABLE_PROGRESS_BARS="${HF_HUB_DISABLE_PROGRESS_BARS:-1}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-}"
export HIP_VISIBLE_DEVICES="${HIP_VISIBLE_DEVICES:-}"
export ROCR_VISIBLE_DEVICES="${ROCR_VISIBLE_DEVICES:-}"

export CHATTERBOX_EXPERIMENTAL_VULKAN_T3="${CHATTERBOX_EXPERIMENTAL_VULKAN_T3:-1}"
export CHATTERBOX_REQUIRE_VULKAN_T3="${CHATTERBOX_REQUIRE_VULKAN_T3:-1}"
export CHATTERBOX_T3_MAX_GEN_LEN="${CHATTERBOX_T3_MAX_GEN_LEN:-420}"
export CHATTERBOX_T3_GGML_WEIGHTS_DIR="${CHATTERBOX_T3_GGML_WEIGHTS_DIR:-/root/chatterbox/exports/ggml_t3_real_prompt_multistep_chunk270_s4_p935}"
export CHATTERBOX_T3_GGML_LIB_PATH="${CHATTERBOX_T3_GGML_LIB_PATH:-/root/chatterbox/libt3_ggml_vulkan_bridge.so}"

exec /root/chatterbox/.venv/bin/python -m uvicorn chatterbox_api:app --host 0.0.0.0 --port "${PORT:-8002}"
